# Generated by Django 3.0.2 on 2020-01-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('external_id', models.PositiveIntegerField()),
                ('pre_evolution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions', to='pokemon.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='StatsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.PositiveIntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pokemon.Pokemon')),
                ('stats_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.StatsType')),
            ],
        ),
    ]
